// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace TrendyMemes.Data.Migrations
{
    public partial class WorkingOnSeeding : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Path",
                table: "Images",
                type: "nvarchar(max)",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Path",
                table: "Images");
        }
    }
}
